version: "3.9"
services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: prisjaktscraperdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"

volumes:
  db_data: