name: Apply terraform if infrastructure has changed
on:
  push:
    branches:
      - "master"
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::220209775221:role/prisjakt-scraper_GithubActionsRole
        aws-region: eu-west-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform