name: Test, build and push Docker image to ECR
on:
  push:
    branches:
      - "master"

permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    uses: haraldvinje/prisjakt_scraper/.github/workflows/run-tests.yml@master

  build-and-push-image-to-ecr:
    needs: run-tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::220209775221:role/prisjakt-scraper_GithubActionsRole
          aws-region: eu-west-1

      - name: Build and push image
        env:
          DB_SECRET_NAME: ${{ secrets.DB_SECRET_NAME }}
        run: |
          cp .env.production .env
          echo DB_SECRET_NAME="$DB_SECRET_NAME" >> .env
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 220209775221.dkr.ecr.eu-west-1.amazonaws.com
          docker build -t prisjakt-scraper-task .
          docker tag prisjakt-scraper-task:latest 220209775221.dkr.ecr.eu-west-1.amazonaws.com/prisjakt-scraper-task:latest
          docker push 220209775221.dkr.ecr.eu-west-1.amazonaws.com/prisjakt-scraper-task:latest